### ISSUE TITLE
The process '/usr/bin/git' failed

### ISSUE THREAD

**Issue by kefniark** [SamKirkland/FTP-Deploy-Action#367]
**Bug Description**
Looks like the problem of https://github.com/SamKirkland/FTP-Deploy-Action/issues/345 is back
The CI which was running for weeks is suddenly broken this morning.

It was working friday on
> git-ftp version 1.6.0 running on Linux 82f985ff95b7 5.15.0-1031-azure #38-Ubuntu SMP Mon Jan 9 12:49:59 UTC 2023 x86_64 GNU/Linux

And now fails with
> git-ftp version 1.6.0 running on Linux 401aba43610a 5.15.0-1031-azure #38-Ubuntu SMP Mon Jan 9 12:49:59 UTC 2023 x86_64 GNU/Linux

So I guess a similar issue to [this one](https://github.com/SamKirkland/FTP-Deploy-Action/issues/345#issuecomment-1353339618), related to some docker image update.

Maybe it could be a good idea to lock the docker image version used at each release to avoid randomly breaking like that.
It would also give the possibility to revert to a previous working version.

**My Action Config**
```yaml
- name: 📡 Deploy files (sync)
   uses: SamKirkland/FTP-Deploy-Action@3.1.2
   with:
      ftp-server: ${{ secrets.FTP_WPENGINE_URL }}
      ftp-username: ${{ secrets.FTP_WPENGINE_USERNAME }}
      ftp-password: ${{ secrets.FTP_WPENGINE_PASSWORD }}
      git-ftp-args: --insecure
```

**My Action Log**
```
14: Forced mode enabled.
15: Auto init if needed.
16: Using syncroot ./ if exists.
17: Insecure SSL/TLS connection allowed
18: Syncroot is './'.
19: fatal: Not a Git project? Exiting...
20: Error: The process '/usr/bin/git' failed with exit code 8
```

**Comment by PetroByte** [comment]
the same with me, no changes on my side and code 8

**Comment by quaytickets** [comment]
Same :-

Mon Jan 30 10:16:54 UTC 2023: git-ftp version 1.6.0 running on Linux 452cbca56881 5.15.0-1031-azure #38-Ubuntu SMP Mon Jan 9 12:49:59 UTC 2023 x86_64 GNU/Linux
 Mon Jan 30 10:16:54 UTC 2023: Forced mode enabled.
 Mon Jan 30 10:16:54 UTC 2023: Auto init if needed.
 Mon Jan 30 10:16:54 UTC 2023: Using syncroot ./ if exists.
 Mon Jan 30 10:16:54 UTC 2023: Insecure SSL/TLS connection allowed
 Mon Jan 30 10:16:54 UTC 2023: Syncroot is './'.
 Mon Jan 30 10:16:54 UTC 2023: fatal: Not a Git project? Exiting...
Error: The process '/usr/bin/git' failed with exit code 8

**Comment by ayDavidGitHere** [comment]
same code 8 error here. help!!!


```
Mon Jan 30 13:51:30 UTC 2023: git-ftp version 1.6.0 running on Linux 2195f1ef734e 5.15.0-1031-azure #38-Ubuntu SMP Mon Jan 9 12:49:59 UTC 2023 x86_64 GNU/Linux
  Mon Jan 30 [13](https://github.com/ayDavidGitHere/nmsg/actions/runs/4044515380/jobs/6954753706#step:4:14):51:30 UTC 2023: Forced mode enabled.
  Mon Jan 30 13:51:30 UTC 2023: Auto init if needed.
  Mon Jan 30 13:51:30 UTC 2023: Using syncroot ./ if exists.
  Mon Jan 30 13:51:30 UTC 2023: Syncroot is './'.
  Mon Jan 30 13:51:30 UTC 2023: fatal: Not a Git project? Exiting...)

```

**Comment by 999digital** [comment]
Same here as of yesterday, still failing today.

**Comment by kefniark** [comment]
Yes still failing, we kinda have to wait on @SamKirkland
Been doing my sftp deployments with FileZilla since yesterday, old school 😄

**Comment by PetroByte** [comment]
Yep, this problem is still existing, has somebody reported it to github? Any message from their side?

**Comment by SamKirkland** [comment]
Going to l look into this tonight!

**Comment by PetroByte** [comment]
I've got replay from github:

<html><body>


  | Paul (GitHub Support)                                                                    Feb 1, 2023, 7:05 AM UTC                                                Hi,Thank you for writing to GitHub Support.I don't believe the error is from GitHub Actions themselves but from the SamKirkland/FTP-Deploy-Action  action you are using (or its dependencies). Such issues are beyond what  GitHub Support can troubleshoot since we don't have visibility into the  logic in the code, and the errors that it throws in case something goes  wrong. The maintainers of the Action would be best placed to  investigate.From the linked issues it sounds like the problems might be with the git-ftp package. Here are a couple of things you could try:Change the runner images, e.g. from ubuntu-latest to macos-latest or windows-latest, and see if you get the same errorTest if you can reproduce the problem on self-hosted runners  to rule out the case that an update to the GitHub-hosted runner images  is causing it. We sometimes see such failures when software in the  runner image is updated (potentially causing a breaking change to a  dependency)Let me know how that goes.Regards, Paul GitHub Support
-- | --



</body>
</html>Paul (GitHub Support)

Feb 1, 2023, 7:05 AM UTC

Hi,

Thank you for writing to GitHub Support.

I don't believe the error is from GitHub Actions themselves but from the SamKirkland/FTP-Deploy-Action action you are using (or its dependencies). Such issues are beyond what GitHub Support can troubleshoot since we don't have visibility into the logic in the code, and the errors that it throws in case something goes wrong. The maintainers of the Action would be best placed to investigate.

From the linked issues it sounds like the problems might be with the git-ftp package. Here are a couple of things you could try:

    Change the runner images, e.g. from ubuntu-latest to macos-latest or windows-latest, and see if you get the same error
    Test if you can reproduce the problem on [self-hosted runners](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners) to rule out the case that an update to the GitHub-hosted runner images is causing it. We sometimes see such failures when software in the runner image is updated (potentially causing a breaking change to a dependency)

Let me know how that goes.

Regards,
Paul
GitHub Support

**Comment by kefniark** [comment]
Yes, Github support can't do much about that kind of code related issue,
An action crashing seem totally out of their scope 😄
At best they will recommend you to use an alternative action

**Comment by PetroByte** [comment]
[Sam Kirkland](https://github.com/SamKirkland) - last time (believe it was 15 dec) - You've written that it was on github side? Have You checked actual issue?

**Comment by SamKirkland** [comment]
This is not a GitHub issue. GitHub happened to be having issues on the same day.

This is the exact same issue as last time. The underlying docker image pushed a breaking update. See **root cause** description this comment https://github.com/SamKirkland/FTP-Deploy-Action/issues/345#issuecomment-1353339618

I just need to update the underlying docker image to a truly stable and working image. Actively looking for a image that meets the criteria.

**Comment by PetroByte** [comment]
please inform about the progress

**Comment by quaytickets** [comment]
> This is not a GitHub issue. GitHub happened to be having issues on the same day.
> 
> This is the exact same issue as last time. The underlying docker image pushed a breaking update. See **root cause** description this comment [#345 (comment)](https://github.com/SamKirkland/FTP-Deploy-Action/issues/345#issuecomment-1353339618)
> 
> I just need to update the underlying docker image to a truly stable and working image. Actively looking for a image that meets the criteria.

Thank you Sam

**Comment by kefniark** [comment]
It start to be quite long, and my coworkers are getting pissed by those deployment issues.
Any ETA? or any temporary fix maybe?
At least some feedback so we can take some decision

**Comment by kefniark** [comment]
I had gave up under pression, and move away from sftp. 🥲
Other sftp actions don't really look more maintained or stable than this one, so I decided to move to ssh/rsync with https://github.com/wpengine/github-action-wpe-site-deploy 

Thanks for the work, I let this issue open if other people are interested by feedback from @SamKirkland
Feel free to close it. 👋

**Comment by SamKirkland** [comment]
Should be resolved now. If someone can re-trigger there action (must be using 
`3.1.2` - that's the only version I patched

**Comment by ermincelikovic** [comment]
@SamKirkland Still fails (with 3.1.2)

**Comment by kqpetter** [comment]
@SamKirkland 
Error: Unable to resolve action `SamKirkland/FTP-Deploy-Action@3.1.2-patch`, unable to find version `3.1.2-patch`

**Comment by ermincelikovic** [comment]
@SamKirkland - still does not work (with v3.1.2-patch) - but seems like it's due to sftp?

```
 Thu Feb  2 08:52:18 UTC 2023: The remote sha1 is saved in file '.git-ftp.log'.
 Thu Feb  2 08:52:18 UTC 2023: Check if curl is functional.
 Thu Feb  2 08:52:18 UTC 2023: fatal: Protocol 'sftp' not supported by curl, exiting...
```

**Comment by SamKirkland** [comment]
> @SamKirkland Error: Unable to resolve action `SamKirkland/FTP-Deploy-Action@3.1.2-patch`, unable to find version `3.1.2-patch`

You are missing the `v`

**Comment by SamKirkland** [comment]
> @SamKirkland - still does not work (with v3.1.2-patch) - but seems like it's due to sftp?
> 
> ```
>  Thu Feb  2 08:52:18 UTC 2023: The remote sha1 is saved in file '.git-ftp.log'.
>  Thu Feb  2 08:52:18 UTC 2023: Check if curl is functional.
>  Thu Feb  2 08:52:18 UTC 2023: fatal: Protocol 'sftp' not supported by curl, exiting...
> ```

Okay thanks. I was worried about that. Will have to dig a bit deeper

**Comment by step-k** [comment]
@SamKirkland `SamKirkland/FTP-Deploy-Action@v3.1.2-patch` - works for me.

**Comment by PetroByte** [comment]
> I had gave up under pression, and move away from sftp. 🥲 Other sftp actions don't really look more maintained or stable than this one, so I decided to move to ssh/rsync with https://github.com/wpengine/github-action-wpe-site-deploy
> 
> Thanks for the work, I let this issue open if other people are interested by feedback from @SamKirkland Feel free to close it. 👋

Current runner version: '2.301.1'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Error: Unable to resolve action `SamKirkland/FTP-Deploy-Action@3.1.2-patch`, unable to find version `3.1.2-patch`



  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.2-patch
      with:
        ftp-server: sftp://server225395.nazwa.pl/migracja/public_html/wp_flexynotes/sezam/
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        git-ftp-args: --insecure

**Comment by PetroByte** [comment]
Uploading files
  /usr/bin/git ftp push --force --auto-init --verbose --syncroot=./ --user=*** --passwd=*** --insecure 
  Thu Feb  2 13:08:04 UTC 2023: git-ftp version 1.6.0 running on Linux 8b8f91928bde 5.15.0-1031-azure #38-Ubuntu SMP Mon Jan 9 12:49:59 UTC 2023 x86_64 Linux
  Thu Feb  2 13:08:04 UTC 2023: Forced mode enabled.
  Thu Feb  2 13:08:04 UTC 2023: Auto init if needed.
  Thu Feb  2 13:08:04 UTC 2023: Using syncroot ./ if exists.
  Thu Feb  2 13:08:04 UTC 2023: Insecure SSL/TLS connection allowed
  Thu Feb  2 13:08:04 UTC 2023: Syncroot is './'.
  Thu Feb  2 13:08:05 UTC 2023: User is '***'.
  Thu Feb  2 13:08:05 UTC 2023: Password is set.
  Thu Feb  2 13:08:05 UTC 2023: CACert is ''.
  Thu Feb  2 13:08:05 UTC 2023: Insecure is '1'.
  Thu Feb  2 13:08:05 UTC 2023: Proxy is ''.
  Thu Feb  2 13:08:05 UTC 2023: The remote sha1 is saved in file '.git-ftp.log'.
  Thu Feb  2 13:08:05 UTC 2023: Check if curl is functional.
  Thu Feb  2 13:08:05 UTC 2023: fatal: Protocol 'sftp' not supported by curl, exiting...
Error: The process '/usr/bin/git' failed with exit code 5

**Comment by gioxx** [comment]
> @SamKirkland `SamKirkland/FTP-Deploy-Action@v3.1.2-patch` - works for me.

Same here. Thanks @SamKirkland.

**Comment by donroyco** [comment]
> @ermincelikovic thanks for the quick response! Looks like i need to push an update to the tag (it's still referencing the old code)
> 
> In the meantime can you use the patched version and let me know how it goes? In your action update the version to `v3.1.2-patch`
> 
> It should look something like `uses: SamKirkland/FTP-Deploy-Action@v3.1.2-patch`

Thank you for the patch @SamKirkland, but for me it is not working, now a different error code pops up:

```yaml
  Thu Feb  2 18:14:03 UTC 2023: The remote sha1 is saved in file '.git-ftp.log'.
  Thu Feb  2 18:14:03 UTC 2023: Check if curl is functional.
  Thu Feb  2 18:14:03 UTC 2023: fatal: Protocol 'sftp' not supported by curl, exiting...
  ::endgroup::
Error: The process '/usr/bin/git' failed with exit code 5
```

**Comment by jengreen115** [comment]
> > @ermincelikovic thanks for the quick response! Looks like i need to push an update to the tag (it's still referencing the old code)
> > In the meantime can you use the patched version and let me know how it goes? In your action update the version to `v3.1.2-patch`
> > It should look something like `uses: SamKirkland/FTP-Deploy-Action@v3.1.2-patch`
> 
> Thank you for the patch @SamKirkland, but unfortunately for me it is not working, now a different error code pops up:
> 
> ```yaml
>   Thu Feb  2 18:14:03 UTC 2023: The remote sha1 is saved in file '.git-ftp.log'.
>   Thu Feb  2 18:14:03 UTC 2023: Check if curl is functional.
>   Thu Feb  2 18:14:03 UTC 2023: fatal: Protocol 'sftp' not supported by curl, exiting...
>   ::endgroup::
> Error: The process '/usr/bin/git' failed with exit code 5
> ```
> 
> If you need help to test any patch, just let me know.

We are receiving this error code now as well with the patch.

**Comment by corymurphy** [comment]
I was still having this issue on 3.1.2, but I fixed it by forking the project and running this prior to the upload. I discovered this by adding a `git branch` step, and it was reporting some issues with the local git repo. I think it has to do with permissions of the directory when running in the debian container.

`git config --global --add safe.directory /github/workspace`

**Comment by walandio** [comment]
Hi Is there an update on this one? I still got the same error 
Error: The process '/usr/bin/git' failed with exit code 8

I have also tried the v3.1.2-patch but still not working.
I am using an sftp connection. Is there a workaround on this one?

**Comment by ahinkle** [comment]
Did anyone find a workaround (in my case for WpEngine)? Back to the old days of Filezilla 😄

**Comment by benjamintemitope** [comment]
> @SamKirkland `SamKirkland/FTP-Deploy-Action@v3.1.2-patch` - works for me.

Thanks! This worked for me 😀.

**Comment by jengreen115** [comment]
v3.1.2-patch is still failing for me with the following error:  `Error: The process '/usr/bin/git' failed with exit code 5`

**Comment by GOUKOU007** [comment]
v3.1.2-patch worked for me too! Thanks!😄

**Comment by jengreen115** [comment]
For everyone who has it working, are you SFTPing up to a server? The last two lines I get before my error read:
```Thu Feb 23 17:15:36 UTC 2023: Check if curl is functional.
  Thu Feb 23 17:15:36 UTC 2023: fatal: Protocol 'sftp' not supported by curl, exiting...```

**Comment by walandio** [comment]
I got the same error.. I am using sftp..

> For everyone who has it working, are you SFTPing up to a server? The last two lines I get before my error read: `Thu Feb 23 17:15:36 UTC 2023: Check if curl is functional. Thu Feb 23 17:15:36 UTC 2023: fatal: Protocol 'sftp' not supported by curl, exiting...`

**Comment by donroyco** [comment]
@SamKirkland I understand that you're likely quite busy, but I was wondering if you might be able to investigate the problem. I appreciate any time and effort you can spare, but please don't feel obligated if you simply don't have the bandwidth right now. 

Thank you in advance for your help, and please let me know if there's anything I can do to assist you.

**Comment by kefniark** [comment]
Sorry guys but those last errors looks different enough and not directly related to the original issue.
The original problem has been fixed in `3.1.2-patch` and this issue should already have been closed long ago.

It feel like this thread became a mix of different problems, can you please create dedicated issues for those.

**Comment by CleanCodeDeveloper** [comment]
Still having the same issue.

excerpt from github action:
```yml
      # Publish website via SFTP
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@3.1.2 # need to stay on 3.1.2 as SFTP support was removed in 4.0
        with:
          ftp-server: ${{ secrets.FTP_SERVER }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public
          git-ftp-args: --insecure
```
log:
```
Run SamKirkland/FTP-Deploy-Action@3.1.[2](https://github.com/CleanCodeDeveloper/*****************/actions/runs/4578682702/jobs/8085601342#step:10:2)
  with:
    ftp-server: ***
    ftp-username: ***
    ftp-password: ***
    local-dir: ./public
    git-ftp-args: --insecure

...

Fri Mar 31 19:57:43 UTC 2023: git-ftp version 1.6.0 running on Linux 9075f7f2e4e1 5.[15](https://github.com/CleanCodeDeveloper/*****************/actions/runs/4578682702/jobs/8085601342#step:10:16).0-1034-azure #41-Ubuntu SMP Fri Feb 10 19:59:45 UTC 2023 x86_64 GNU/Linux
  Fri Mar 31 19:57:43 UTC 2023: Forced mode enabled.
  Fri Mar 31 19:57:43 UTC 2023: Auto init if needed.
  Fri Mar 31 19:57:43 UTC 2023: Using syncroot ./public if exists.
  Fri Mar 31 19:57:43 UTC 2023: Insecure SSL/TLS connection allowed
  Fri Mar 31 19:57:43 UTC 2023: Syncroot is './public/'.
  Fri Mar 31 19:57:43 UTC 2023: fatal: Not a Git project? Exiting...
Error: The process '/usr/bin/git' failed with exit code 8
```

Note: 
I got the same result with `SamKirkland/FTP-Deploy-Action@v3.1.2-patch`.

**Comment by jemshit** [comment]
Did anyone solve `Protocol 'sftp' not supported by curl` error?
I read we need to install `curl` from source code, but I couldn't find script to do so on ubuntu images provided by github actions.

**Comment by jemshit** [comment]
Ubuntu 20.04: `Not a Git project? Exiting...`
Ubuntu 24.02: `Protocol 'sftp' not supported by curl, exiting...`
